# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dacdc9f8fc578d9048fcc56d59491e54fd498a35d889954199537fb1a5d9a94a7c7f489739f50801223683c10d6be49f8bb3b654afda7a561dcbae16ac7031a

test:
  secret_key_base: 0f78c7251cdc37f2344c912c7940172d7ed3763fcf97a963b501cc547159a05e01c907d4e7f7f3afaaa027353dd1d9b09de6cb9ef17733da661949f2a4d32757

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
