export const BATCH_FETCHING_DATA = 'BATCH_FETCHING_DATA'
export const BATCH_FETCHING_DATA_SUCCESS = 'BATCH_FETCHING_DATA_SUCCESS'
export const BATCH_FETCHING_DATA_FAILURE = 'BATCH_FETCHING_DATA_FAILURE'
