export const BATCH_FETCHING_DATA = 'BATCH_FETCHING_DATA'
export const BATCH_FETCHING_DATA_SUCCESS = 'BATCH_FETCHING_DATA_SUCCESS'
export const BATCH_FETCHING_DATA_FAILURE = 'BATCH_FETCHING_DATA_FAILURE'

export const ROBOT_EXTINGUISHING = 'ROBOT_EXTINGUISHING'
export const ROBOT_EXTINGUISHED = 'ROBOT_EXTINGUISHED'
export const ROBOT_EXTINGUISH_FAILED = 'ROBOT_EXTINGUISH_FAILED'