export const BATCH_FETCHING_DATA = 'BATCH_FETCHING_DATA'
export const BATCH_FETCHING_DATA_SUCCESS = 'BATCH_FETCHING_DATA_SUCCESS'
export const BATCH_FETCHING_DATA_FAILURE = 'BATCH_FETCHING_DATA_FAILURE'

export const ROBOT_EXTINGUISHING = 'ROBOT_EXTINGUISHING'
export const ROBOT_EXTINGUISHED = 'ROBOT_EXTINGUISHED'
export const ROBOT_EXTINGUISH_FAILED = 'ROBOT_EXTINGUISH_FAILED'

export const ROBOTS_RECYCLING = 'ROBOTS_RECYCLING'
export const ROBOTS_RECYCLED = 'ROBOTS_RECYCLED'
export const ROBOTS_RECYCLING_FAILED = 'ROBOTS_RECYCLING_FAILED'

export const ROBOT_ADD_TO_SHIPMENT = 'ROBOT_ADD_TO_SHIPMENT' 
export const ROBOT_REMOVE_FROM_SHIPMENT = 'ROBOT_REMOVE_FROM_SHIPMENT'
export const ROBOT_SHIPPING = 'ROBOT_SHIPPING'
export const ROBOT_SHIPPED = 'ROBOT_SHIPPED'
